name: CI Pipeline

on:
  push:
    branches:
      - main
      - developt
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar dependencias del frontend
      - name: Install frontend dependencies
        working-directory: Dana_aplication_4/Dana/Client
        run: npm ci

      # Ejecutar pruebas del frontend
      - name: Run frontend tests
        working-directory: Dana_aplication_4/Dana/Client
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Establece la variable de entorno MONGO_URI
        run: npm run test

      # Instalar dependencias del backend
      - name: Install backend dependencies
        working-directory: Dana_aplication_4/Dana/Server
        run: npm ci

      # Ejecutar pruebas del backend (Ignorar error si algo falla)
      - name: Run backend tests
        working-directory: Dana_aplication_4/Dana/Server
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm run test
        continue-on-error: true  # Esto permitirá que el job siga incluso si esta parte falla, esto lo hacemos ,ya que, el cluster de mongo va mal
