name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Para instalar dependencias de Dana/Client
      - name: Install dependencies for Client
        run: |
          cd Dana_aplication_4\Dana\Client
          npm ci

      # Para instalar dependencias de Dana/Server
      - name: Install dependencies for Server
        run: |
          cd Dana_aplication_4\Dana\Server
          npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: windows-latest
    if: success()

    steps:
      - name: Deploy application
        run: echo "Desplegando aplicación..."

