name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Usa Windows, pero podrías cambiarlo a ubuntu-latest si prefieres Linux.

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Imprimir el directorio de trabajo actual (debug)
      - name: Print working directory
        run: pwd

      # Instalar dependencias del frontend
      - name: Install frontend dependencies
        working-directory: Dana_aplication_4/Dana/Client
        run: npm ci

      # Ejecutar pruebas del frontend
      - name: Run frontend tests
        working-directory: Dana_aplication_4/Dana/Client
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Establece la variable de entorno MONGO_URI
        run: npm run test

      # Instalar dependencias del backend
      - name: Install backend dependencies
        working-directory: Dana_aplication_4/Dana/Server
        run: npm ci

      # Ejecutar pruebas del backend
      - name: Run backend tests
        working-directory: Dana_aplication_4/Dana/Server
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Establece la variable de entorno MONGO_URI
        run: npm run test